# shared variables

image_url = "?"
screen_name = "?"
description = "?"
location = "location: ?"
verified = "?"
created_at = "?"
tweets = "?"
followers = "?"
following = "?"
average_tweet_time = "?"
average_tweet_retweets = "?"
average_tweet_favorites = "?"
followback_percentage = "?"
followback_total = "?"
wordcloud_image = "?"
most_tweets_per_day = "?"
most_tweets_day = "?"
time_taken_1st_tweet = "?"
time_taken_100_tweets = "?"
